# Generated by Django 2.2.4 on 2019-10-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='shop/product-images')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv?')),
            ],
        ),
    ]
